#define WRITEBIT(WORD,BITPOS,BIT) WORD=((WORD&~(1<<BITPOS))|(BIT<<BITPOS))

#define WRITEBYTE(WORD,BITPOS,BYTE) WORD=((WORD&~(255<<BITPOS))|(BYTE<<BITPOS))

#define WRITENIBBLE(WORD,BITPOS,NIBBLE) WORD=((WORD&~(15<<BITPOS))|(NIBBLE<<BITPOS))

#define CLRBIT(WORD,BIT) (WORD|=(1<<BIT))

#define SETBIT(WORD,BIT)(WORD&~(1<<BITPOS))

#define CPLBIT(WORD,BIT) (WORD^=1<<BIT)

#define READWRITEBIT(WORD,DBIT,SBIT) WORD=(WORD&~(1<<DBIT))|(((WORD>>SBIT)&1)<<DBIT))






